name: OpenAPI 3 CI

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install @apidevtools/json-schema-ref-parser

      - name: OpenAPI 3 resolve
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const $RefParser = require('@apidevtools/json-schema-ref-parser');

            async function resolverOpenAPI() {
              try {
                const outputFileName = 'resolved-openapi3.yaml';
                const openapiResolved = await $RefParser.bundle('openapi3.yaml');
                const openapiResolvedYAML = yaml.dump(openapiResolved, { indent: 2 });
                fs.writeFileSync(outputFileName, openapiResolvedYAML);
                console.log(`Check out the resolved file at: ${outputFileName}`);
              } catch (err) {
                console.error(err);
              }
            }

            resolverOpenAPI();

      - name: Upload resolved OpenAPI 3
        uses: actions/upload-artifact@v4
        with:
          name: resolved-openapi3
          path: resolved-openapi3.yaml

  validate-openapi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download resolved OpenAPI 3
        uses: actions/download-artifact@v4
        with:
          name: resolved-openapi3

      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli

      - name: Set exposure type
        uses: actions/github-script@v7
        with:
          script: |
            const repoName = context.repo.name;
            const exposureType = repoName.endsWith('external') ? 'external' : 'internal';
            core.exportVariable('EXPOSURE_TYPE', exposureType);
            console.log(`EXPOSURE_TYPE set to "${exposureType}".`);

      - name: Checkout renanphellip/openapi-workflows
        uses: actions/checkout@v4
        with:
          repository: renanphellip/openapi-workflows
          ref: main
          path: openapi-workflows

      - name: Validate resolved OpenAPI 3
        env:
          CUSTOM_RULESET_NAME: '${{ env.EXPOSURE_TYPE }}-ruleset.yaml'
        run: |
          spectral lint resolved-openapi3.yaml --ruleset openapi-workflows/rulesets/${CUSTOM_RULESET_NAME}
